spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
    url: jdbc:postgresql://localhost:5432/student_dashboard
  jpa:
    hibernate:
      ddl-auto: create